services:
  ffc-rpa-api-gateway:
    build:
      context: .
      target: production
    image: ffc-rpa-api-gateway
    container_name: ffc-rpa-api-gateway
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-rpa-api-gateway-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      RPA_API: ${RPA_API}
      CERTIFICATE: ${CERTIFICATE}
      KEY: ${KEY}
      PASSPHRASE: ${PASSPHRASE}

