{{- include "ffc-helm-library.container-config-map" (list . "ffc-rpa-api-gateway.config-map") -}}
{{- define "ffc-rpa-api-gateway.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  RPA_API: {{ quote .Values.container.rpaApi }}
{{- end -}}
