{{- include "ffc-helm-library.container-secret" (list . "ffc-rpa-api-gateway.container-secret") -}}
{{- define "ffc-rpa-api-gateway.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- end }}
  CERITFICATE: {{ quote .Values.container.certificate }}
  KEY: {{ quote .Values.container.key }}
  PASSPHRASE: {{ quote .Values.container.passphrase }}
{{- end -}}
