environment: development
name: ffc-rpa-api-gateway
namespace: ffc-rpa
workstream: ffc-rpa
image: ffc-rpa-api-gateway

labels: {}

aadPodIdentity: true

appInsights:
  key:

containerConfigMap:
  name: ffc-rpa-api-gateway-config-map

containerSecret:
  name: ffc-rpa-api-gateway-container-secret
  type: Opaque

service:
  port: 80
  type: ClusterIP

deployment:
  restartPolicy: Always
  priorityClassName: high
  replicas: 1
  minReplicas: 1
  maxReplicas: 4
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000
  rpaApi:
  certificate:
  key:
  passphrase:

ingress:
  class: nginx
  endpoint: ffc-rpa-api-gateway
  server: example.com

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
